export const Punjab = [
  { value: "Abdul Hakim", label: "Abdul Hakim ", ulabel: "" },
  { value: "Ahmadpur East", label: "Ahmadpur East", ulabel: "" },
  { value: "Attock Khurd", label: "Attock Khurd", ulabel: "" },
  { value: "Bahawalpur", label: "Bahawalpur" },
  { value: "Bhakkar", label: "Bhakkar" },
  { value: "Bhalwal", label: "Bhalwal" },
  { value: "Chenab Nagar", label: "Chenab Nagar" },
  { value: "Chiniot", label: "Chiniot" },
  { value: "Chishtian", label: "Chishtian" },
  { value: "Chunian", label: "Chunian" },
  { value: "Dera Ghazi Khan", label: "Dera Ghazi Khan" },
  { value: "Dipalpur", label: "Dipalpur" },
  { value: "Faisalabad", label: "Faisalabad" },
  { value: "Gilwala", label: "Gilwala" },
  { value: "Gojra", label: "Gojra" },
  { value: "Gujranwala", label: "Gujranwala" },
  { value: "Gujrat", label: "Gujrat" },
  { value: "Harunabad", label: "Harunabad" },
  { value: "Hasilpur", label: "Hasilpur" },
  { value: "Hassan Abdal", label: "Hassan Abdal" },
  { value: "Hujra Shah Muqim", label: "Hujra Shah Muqim" },
  { value: "Jalalpur Jattan", label: "Jalalpur Jattan" },
  { value: "Jaranwala", label: "Jaranwala" },
  { value: "Jhang City", label: "Jhang City" },
  { value: "Kabirwala", label: "Kabirwala" },
  { value: "Kahror Pakka", label: "Kahror Pakka" },
  { value: "Kamalia", label: "Kamalia" },
  { value: "Kasur", label: "Kasur" },
  { value: "Khanpur", label: "Khanpur" },
  { value: "Kharian", label: "Kharian" },
  { value: "Khushab", label: "Khushab" },
  { value: "Kot Addu", label: "Kot Addu" },
  { value: "Kundian", label: "Kundian" },
  { value: "Lahore", label: "Lahore" },
  { value: "Lala Musa", label: "Lala Musa" },
  { value: "Mandi Bahauddin", label: "Mandi Bahauddin" },
  { value: "Mandi Burewala", label: "Mandi Burewala" },
  { value: "Mian Channun", label: "Mian Channun" },
  { value: "Mianwali", label: "Mianwali" },
  { value: "Multan", label: "Multan" },
  { value: "Muridke", label: "Muridke" },
  { value: "Murree", label: "Murree" },
  { value: "Muzaffargarh", label: "Muzaffargarh" },
  { value: "Nankana Sahib", label: "Nankana Sahib" },
  { value: "Okara", label: "Okara" },
  { value: "Pakpattan", label: "Pakpattan" },
  { value: "Pasrur", label: "Pasrur" },
  { value: "Pattoki", label: "Pattoki" },
  { value: "Rahimyar Khan", label: "Rahimyar Khan" },
  { value: "Rawalpindi", label: "Rawalpindi" },
  { value: "Saddiqabad", label: "Saddiqabad" },
  { value: "Sahiwal", label: "Sahiwal" },
  { value: "Sambrial", label: "Sambrial" },
  { value: "Samundri", label: "Samundri" },
  { value: "Sargodha", label: "Sargodha" },
  { value: "Shakargarh", label: "Shakargarh" },
  { value: "Shekhupura", label: "Shekhupura" },
  { value: "Shujaabad", label: "Shujaabad" },
  { value: "Sialkot City", label: "Sialkot City" },
];
export const sindh = [
  { value: "Badin", label: "Badin" },
  { value: "Dadu", label: "Dadu" },
  { value: "Ghotki", label: "Ghotki" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Jacobabad", label: "Jacobabad" },
  { value: "Jamshoro", label: "Jamshoro" },
  { value: "Karachi Central", label: "Karachi Central" },
  { value: "Kashmore ", label: "Kashmore " },
  { value: "Khairpur", label: "Khairpur" },
  { value: "Larkana", label: "Larkana" },
  { value: "Matiari", label: "Matiari" },
  { value: "Mirpur Khas", label: "Mirpur Khas" },
  { value: "Naushahro Firoze", label: "Naushahro Firoze" },
  { value: "Shaheed Benazirabad", label: "Shaheed Benazirabad" },
  { value: "Qambar Shahdadkot", label: "Qambar Shahdadkot" },
  { value: "Sanghar", label: "Sanghar" },
  { value: "Shikarpur", label: "Shikarpur" },
  { value: "Sukkur", label: "Sukkur" },
  { value: "Tando Allahyar", label: "Tando Allahyar" },
  { value: "Tando Muhammad Khan", label: "Tando Muhammad Khan" },
  { value: "Tharparkar", label: "Tharparkar" },
  { value: "Thatta", label: "Thatta" },
  { value: "Umerkot", label: "Umerkot" },
  { value: "Sujawal", label: "Sujawal" },
  { value: "Karachi East", label: "Karachi East" },
  { value: "Karachi South", label: "Karachi South" },
  { value: "Karachi West", label: "Karachi West" },
  { value: "Korangi", label: "Korangi" },
  { value: "Malir", label: "Malir" },

  
];
export const KPK = [
  { value: "Bajaur", label: "Bajaur" },
  { value: "Bannu", label: "Bannu" },
  { value: "Batagram", label: "Batagram" },
  { value: "Buner", label: "Buner" },
  { value: "Charsadda", label: "Charsadda" },
  { value: "Dera Ismail Khan", label: "Dera Ismail Khan" },
  { value: "Hangu", label: "Hangu" },
  { value: "Haripur", label: "Haripur" },
  { value: "Karak", label: "Karak" },
  { value: "Khyber", label: "Khyber" },
  { value: "Kohat", label: "Kohat" },
  { value: "Kolai Pallas", label: "Kolai Pallas" },
  { value: "Kurram", label: "Kurram" },
  { value: "Lakki Marwat", label: "Lakki Marwat" },
  { value: "Lower Chitral", label: "Lower Chitral" },
  { value: "Lower Dir", label: "Lower Dir" },
  { value: "Lower Kohistan", label: "Lower Kohistan" },
  { value: "Malakand", label: "Malakand" },
  { value: "Mansehra", label: "Mansehra" },
  { value: "Mardan", label: "Mardan" },
  { value: "Mohmand", label: "Mohmand" },
  { value: "North Waziristan", label: "North Waziristan" },
  { value: "Nowshera", label: "Nowshera" },
  { value: "Orakzai", label: "Orakzai" },
  { value: "Peshawar", label: "Peshawar" },
  { value: "Shangla", label: "Shangla" },
  { value: "South Waziristan", label: "South Waziristan" },
  { value: "Swabi", label: "Swabi" },
  { value: "Swat", label: "Swat" },
  { value: "Tank", label: "Tank" },
  { value: "Tor Ghar", label: "Tor Ghar" },
  { value: "Upper Chitral", label: "Upper Chitral" },
  { value: "Upper Dir", label: "Upper Dir" },
  { value: "Upper Kohistan", label: "Upper Kohistan" },
  
];

export const feralCapital = [{ value: "Islamabad", label: "Islamabad" }];
export const Blochistan = [
  
 
  { value: "Awaran", label:   "Awaran" },
  { value: "Barkhan", label:   "Barkhan" },
  { value: "Chagai", label:   "Chagai" },
  { value: "Dera Bugti", label:   "Dera Bugti" },
  { value: "Duki", label:   "Duki" },
  { value: "Gwadar", label:   "Gwadar" },
  { value: "Harnai", label:   "Harnai" },
  { value: "Jafarabad", label:   "Jafarabad" },
  { value: "Jhal Magsi", label:   "Jhal Magsi" },
  { value: "Kachhi", label:   "Kachhi" },
  { value: "Kalat", label:   "Kalat" },
  { value: "Kech", label:   "Kech" },
  { value: "Kharan", label:   "Kharan" },
  { value: "Khuzdar", label:   "Khuzdar" },
  { value: "Killa Abdullah", label:   "Killa Abdullah" },
  { value: "Kohlu", label:   "Kohlu" },
  { value: "Lasbela", label:   "Lasbela" },
  { value: "Loralai", label:   "Loralai" },
  { value: "Mastung", label:   "Mastung" },
  { value: "Musakhel", label:   "Musakhel" },
  { value: "Naseerabad", label:   "Naseerabad" },
  { value: "Nushki", label:   "Nushki" },
  { value: "Panjgur", label:   "Panjgur" },
  { value: "Pishin", label:   "Pishin" },
  { value: "Qilla Saifullah", label:   "Qilla Saifullah" },
  { value: "Quetta", label:   "Quetta" },
  { value: "Shaheed Sikandarabad", label:   "Shaheed Sikandarabad" },
  { value: "Sherani", label:   "Sherani" },
  { value: "Sibi", label:   "Sibi" },
  { value: "Sohbatpur", label:   "Sohbatpur" },
  { value: "Washuk", label:   "Washuk" },
  { value: "Zhob", label:   "Zhob" },
  { value: "Ziarat", label:   "Ziarat" },


  


];
export const Kashmir = [
  { value: "Bagh", label: "Bagh" },
  { value: "Bhimber", label: "Bhimber" },
  { value: "Hattian", label: "Hattian" },
  { value: "Haveli", label: "Haveli" },
  { value: "Kotli", label: "Kotli" },
  { value: "Mirpur", label: "Mirpur" },
  { value: "Muzaffarabad", label: "Muzaffarabad" },
  { value: "Neelum", label: "Neelum" },
  { value: "Poonch", label: "Poonch" },
  { value: "Sudhnutti", label: "Sudhnutti" },

  
];
export const fruits = [
  { value: "Citrus", lable: "Citrus", ulabel: "مالٹے" },
  { value: "Mango", lable: "Mango", ulabel: "آم" },
  { value: "Bannana", lable: "Bannana", ulabel: "کیلا" },
  { value: "Apple", lable: "Apple", ulabel: "سیب" },
  { value: "Grapes", lable: "Grapes", ulabel: "انگور" },
  { value: "Pomegranate", lable: "Pomegranate", ulabel: "انار" },
  { value: "Guava", lable: "Guava", ulabel: "امرود" },
  { value: "Dates", lable: "Dates", ulabel: "کھجور" },
  { value: "Apricots", lable: "Apricots", ulabel: "خوبانئ" },
  { value: "Peach", lable: "Peach", ulabel: "آڑو" },
  { value: "Pear", lable: "Pear", ulabel: "ناشپاتی" },
  { value: "Plum", lable: "Plum", ulabel: "آلوبخارہ" },
  { value: "Fig", lable: "Fig", ulabel: "انجیر" },
  { value: "Almond", lable: "Almond", ulabel: "بادام" },

  { value: "Jaman", lable: "Jaman", ulabel: "جامن" },
  { value: "Litche", lable: "Litche", ulabel: "لئچئ" },
  { value: "Phalsa", lable: "Phalsa", ulabel: "فالسا" },
  { value: "Walnut", lable: "Walnut", ulabel: "اخروٹ" },
  { value: "Ber", lable: "Ber", ulabel: "بئر" },
  { value: "Loquat", lable: "Loquat", ulabel: "لوکاٹ" },
  { value: "Mulbery", lable: "Mulbery", ulabel: "شھتوت" },
  { value: "Strawberry", lable: "Strawberry", ulabel: "اسٹرابیری" },
  { value: "Chiko", lable: "Chiko", ulabel: "چیکو" },
  { value: "Coconut", lable: "Coconut", ulabel: "ناریل" },
  { value: "Cherry", lable: "Cherry", ulabel: "چیری" },
  { value: "Pistachio", lable: "Pistachio", ulabel: "پستھ" },

  { value: "Papaya", lable: "Papaya", ulabel: "پپیتا" },

  { value: "Persimmon", lable: "Persimmon", ulabel: "جاپانی پھل" },

  { value: "Melon", lable: "Melon", ulabel: "خربوزہ" },
  { value: "Olive", lable: "Olive", ulabel: "زیتون" },
  { value: "Pine", lable: "Pine", ulabel: "پائن نٹ" },
  { value: "Imli", lable: "Imli", ulabel: "املی" },
  { value: "Star fruit", lable: "Star fruit", ulabel: "سٹار فروٹ" },
  { value: "Tangerine", lable: "Tangerine", ulabel: "ٹینجیرین" },
  { value: "Rasp berry", lable: "Rasp berry", ulabel: "رس بھری" },
  { value: "Quince", lable: "Quince", ulabel: "سفرجل" },
];
export const Vegitables = [
  { value: "Beans", lable: "Beans", ulabel: "پھلیاں" },
  { value: "Beet", lable: "Beet", ulabel: "چقندر" },
  { value: "Bitterground", lable: "Bitterground", ulabel: "کریلا" },
  { value: "Brassica", lable: "Brassica", ulabel: "براسیکا" },
  { value: "Brinjal", lable: "Brinjal", ulabel: "بئنگن" },
  { value: "Cabbage", lable: "Cabbage", ulabel: "گوبھی" },
  { value: "Carrot", lable: "Carrot", ulabel: "گاجر" },
  { value: "Cauliflower", lable: "Cauliflower", ulabel: "گوبھی" },
  { value: "Chilli", lable: "Chilli", ulabel: "مرچ" },
  { value: "Coriander", lable: "Coriander", ulabel: "دھنیا" },
  { value: "Cucumber", lable: "Cucumber", ulabel: "کھیرا" },
  { value: "Garlic", lable: "Garlic", ulabel: "لہسن" },
  { value: "Ginger", lable: "Ginger", ulabel: "ادرک" },
  { value: "Gourd", lable: "Gourd", ulabel: "لوکئ" },
  { value: "Knoikhol", lable: "Knoikhol", ulabel: "جنگلئ گوبھئ" },
  { value: "Lemon", lable: "Lemon", ulabel: "لیموں" },
  { value: "Luffa", lable: "Luffa", ulabel: "تورئ" },
  { value: "Mint", lable: "Mint", ulabel: "پودئنھ" },
  { value: "Okra", lable: "Okra ", ulabel: "بھنڈی" },
  { value: "Onion", lable: "Onion", ulabel: "پیاز" },
  { value: "Peas", lable: "Peas", ulabel: "مٹر" },
  { value: "Potato", lable: "Potato", ulabel: "آلو" },
  { value: "Pumpkin", lable: "Pumpkin", ulabel: "کدو" },
  { value: "Radish", lable: "Radish", ulabel: "گاجر" },
  { value: "Spinach", lable: "Spinach", ulabel: "پالک" },
  { value: "Tomato", lable: "Tomato", ulabel: "ٹماٹر" },

  { value: "Turnip", lable: "Turnip", ulabel: "شلجم" },

  { value: "Yam", lable: "Yam", ulabel: "شکر قندی" },

  { value: "Arum", lable: "Arum", ulabel: "اروئ" },
  { value: "Bottle Gourd", lable: "Bottle Gourd", ulabel: "گئا کدو" },
  { value: "Fenugreek", lable: "Fenugreek", ulabel: "میتھی" },
  { value: "Sponge gourd", lable: "Sponge gourd", ulabel: "تورئ" },
  { value: "Tinda gord", lable: "Tinda gord", ulabel: "ٹئنڈھ" },
  { value: "Sweet potato", lable: "Sweet potato", ulabel: "شکر قندی" },
  { value: "Turmeric", lable: "Turmeric", ulabel: "ھلدئ" },
  { value: "Musk Melon", lable: "Musk Melon", ulabel: "کستورئ خربوزھ" },
];

export const FiberCrops = [
  { value: "Cotton", lable: "Cotton", ulabel: "کپاس" },
  { value: "Jute", lable: "Jute", ulabel: "سٹیویا" },
];
export const Months = [
  { value: "January", lable: "Januaury" },
  { value: "Faburary", lable: "Faburary" },
  { value: "March", lable: "March" },
  { value: "April", lable: "April" },
  { value: "May", lable: "May" },
  { value: "June", lable: "June" },

  { value: "July", lable: "July" },
  { value: "August", lable: "August" },
  { value: "September", lable: "September" },
  { value: "October", lable: "October" },
  { value: "November", lable: "November" },
  { value: "December", lable: "December" },
];

export const FoodLegumes = [
  {
    value: "Kalay Chany/Chickpea",
    lable: "Kalay Chany/Chickpea",
    ulabel: "کالے چنی/چنا",
  },
  {
    value: " White Channy/ White gram",
    lable: " White Channy/ White gram",
    ulabel: "سفید چنے/ سفید چنے",
  },
  { value: "Mung beans", lable: "Mung beans", ulabel: "مینگ پھلیاں" },
  {
    value: "Mash/Black gram",
    lable: "Mash/Black gram",
    ulabel: "میش / سیاہ گرام",
  },
  { value: "Moong", lable: "Moong", ulabel: "مونگ" },
  { value: "Gram", lable: "Gram", ulabel: "گرام" },

  { value: "Field pea", lable: "Field pea", ulabel: "فیلڈ پیا" },
  { value: "Lentil", lable: "Lentil", ulabel: "دال" },
  { value: "Pigeon pean", lable: "Pigeon pean", ulabel: "کبوتر پیان" },
  { value: "Lobia/Cowpea", lable: "Lobia/Cowpea", ulabel: "لوبیا/کاؤپیا" },

  { value: "Rawan/Cowpea", lable: "Rawan/Cowpea", ulabel: "راون / کاؤپیا" },
];

export const CEREALCROPS = [
  { value: "Wheat", lable: "Wheat", ulabel: "گندم" },
  { value: "Barley", lable: "Barley", ulabel: "جلی" },
  { value: "Rice", lable: "Rice", ulabel: "چاول" },
  { value: "Maize", lable: "Maize", ulabel: "مکئی" },
  { value: "GreatMillet", lable: "GreatMillet", ulabel: "عظیم باجرا" },
  { value: "Pearl Millet", lable: "Pearl Millet", ulabel: "موتی باجرا" },
];
export const OilSeedCrops = [
  {
    value: "Yellow sarsson/Rapseed",
    lable: "Yellow sarsson/Rapseed",
    ulabel: "پیلا سارسسن / ریپسیڈ۔",
  },
  {
    value: " Ghobi sarsoon/Rapseed",
    lable: " Ghobi sarsoon/Rapseed",
    ulabel: "پیلا سارسسن / ریپسیڈ۔",
  },
  {
    value: "Raya/ Indian mustard",
    lable: "Raya/ Indian mustard",
    ulabel: "غیبی سرسون/ ریپسیڈ۔",
  },
  {
    value: "Taranera mustard",
    lable: "Taranera mustard",
    ulabel: "ترانے سرسوں ",
  },
  { value: "Canola/ Rapseed", lable: "Canola/ Rapseed", ulabel: "کینولا" },

  { value: "Peanut", lable: "Peanut", ulabel: "مونگفلی" },
  { value: "Sunflower", lable: "Sunflower", ulabel: "سورج فلو" },
  { value: "Maize", lable: "Maize", ulabel: "مکئی" },
  { value: "Olive", lable: "Olive", ulabel: "زیتون" },
  { value: "Kala till", lable: "Kala till", ulabel: "کلا تک تک" },

  {
    value: "Sufaid till/ sesame",
    lable: "Sufaid till/ sesame",
    ulabel: "سوفڈ تک / سیسم",
  },
  { value: "Alsi/Linseed", lable: "Alsi/Linseed", ulabel: "السی / السی" },
  {
    value: "Guar/ Cluster bean",
    lable: "Guar/ Cluster bean",
    ulabel: "گار / کلسٹر بین",
  },
  { value: "Cotton", lable: "Cotton", ulabel: "کپاس" },
];
export const ForageCrops = [
  { value: "Barseem", lable: "Barseem", ulabel: "باریسیم" },
  { value: " Persian Clover", lable: " Persian Clover", ulabel: "فارسی  " },
  { value: "Cluster bean", lable: "Cluster bean", ulabel: "کلسٹر بین" },
  { value: "Chari/Shorgum", lable: "Chari/Shorgum", ulabel: "چرئ" },
  { value: "Taranera mustard", lable: "Taranera mustard", ulabel: "ایٹ" },
  { value: "Oat", lable: "Oat", ulabel: "مکئی" },

  { value: "Haloon", lable: "Haloon", ulabel: "ہیلو" },
  { value: "Cheena", lable: "Cheena", ulabel: "سینہ" },
  { value: "Jantar", lable: "Jantar", ulabel: "جنانت" },
  { value: "Mott. Grass", lable: "Mott. Grass", ulabel: "مٹ. گھاس" },
  { value: "Maize", lable: "Maize", ulabel: "جلی" },
];
export const sugarCrops = [
  { value: "Sugarcane", lable: "Sugarcane", ulabel: "گنا" },
  { value: "Sugarbeat", lable: "Sugarbeat", ulabel: "چکندر" },
  { value: "Stevia", lable: "Stevia", ulabel: "سٹیویا" },
];

export const Cattles=[
 
  { value: "Buffalos", lable: "Buffalos", ulabel: "بھینسیں" },
  { value: "Goats", lable: "Goats", ulabel: "بکرے" },
  { value: "Camels", lable: "Camels", ulabel: "اونٹ" },
  { value: "Dumba", lable: "Dumba", ulabel: "دومبا" },
  { value: "Chatra", lable: "Chatra", ulabel: "چھترا" },


  
]


export const Machines=[
  { value: "Tractors", lable: "Tractors", ulabel: "ٹریکٹر" },
  { value: "Combine Harvesters", lable: "Combine Harvesters", ulabel: "کمبائن ہارویسٹر" },
  { value: "Cultivators", lable: "Cultivators", ulabel: "کاشتکار" },
  { value: "Cultipacker", lable: "Cultipacker", ulabel: "کلٹی پیکر" },
  { value: "Harrow", lable: "Harrow", ulabel: "ہیرو" },
  { value: "Subsoiler", lable: "Subsoiler", ulabel: "سب سوائلر" },
  { value: "Rotator", lable: "Rotator", ulabel: "روٹیٹر" },
  { value: "Broadcast seeder", lable: "Broadcast seeder", ulabel: "براڈکاسٹ سیڈر" },
  { value: "Planter", lable: "Planter", ulabel: "پللاننٹر" },
  { value: "Seed Driller", lable: "Seed Driller", ulabel: "بیج ڈرل" },
  { value: "Fertilizer Spreader", lable: "Fertilizer Spreader", ulabel: "کھاد پھیلانے والا" },
  { value: "Trans-planter", lable: "Trans-planter", ulabel: "ٹرانس پلانٹر" },
  { value: "Drip Irrigation Systems", lable: "Drip Irrigation Systems", ulabel: "ڈرپ ایریگیشن سسٹم" },
  { value: "Weight Sorter", lable: "Weight Sorter", ulabel: "وزن چھانٹنے والا" },
  { value: "Round Baler", lable: "Round Baler", ulabel: "گول بیلر" },
  { value: "Sprayers", lable: "Sprayers", ulabel: "سپریر" },
  { value: "Irrigation Pumps", lable: "Irrigation Pumps", ulabel: "آبپاشی پمپس  " },
  { value: "Pickers, Fruits, Hand, Base Metal", lable: "Pickers, Fruits, Hand, Base Metal", ulabel: "چننے والے، پھل، ہاتھ، بیس میٹل" },
  { value: "Diggers, Seeders", lable: "Diggers, Seeders", ulabel: "کھودنے والا، بیج لگانے والا" },
  { value: "Sprinklers", lable: "Sprinklers", ulabel: "چھڑکنے والے" },
  { value: "Cotton Gins and Parts", lable: "Cotton Gins and Parts", ulabel: "کاٹن جنز اور پارٹس" },



]

